services:
  - type: web
    name: blackquiet-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PROXY_HOST
        value: niceproxy.io
      - key: PROXY_PORT
        value: 17521
      - key: PROXY_USER
        value: black_rIxx-country-CA-isp-as11260_eastlink-ssid-RRZby1eS6k
      - key: PROXY_PASS
        value: Kouame07
      - key: SMTP_HOST
        value: smtp.eastlink.ca
      - key: SMTP_PORT
        value: 25
